version: '3.9'

services:
  jwt-db:
    container_name: jwt-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  login-app:
    container_name: login-app
    image: backend-login-jwt
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://jwt-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - JWT_SECRET_KEY=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - JWT_EXPIRATION=43200000
      # Aqui iria la creacion de un super usuario base

    depends_on:
      - jwt-db

